### ISSUE TITLE
Can veldrid be a replacement for SkiaSharp?

### ISSUE THREAD

**Issue by sgf** [veldrid/veldrid#543]
The SkiaSharp dll file is too large, close to 10mb.
I'm looking for a 2d graphics library developed in pure C#

**Comment by Nebula-Developer** [comment]
Veldrid is used to interact with other graphical APIs like Vulkan, OpenGL, Metal and Direct3D. It's just an agnostic API that can render to low-level 3D APIs, whereas SkiaSharp is a feature-full vector 2D graphics library.

It depends on what you are trying to do, if its just simple 2D rendering, then Veldrid will work, but will be far lower level in comparison to SkiaSharp. It depends on how much control and flexibility you want with the drawing logic.

**Comment by sgf** [comment]
tks
